local beautiful = require ("beautiful")

launcher = egregious.widget.launcher()
soundwidget = egregious.widget.soundwidget()
battwidget = egregious.widget.battwidget()
wifiwidget = egregious.widget.wifiwidget()
cpuwidget = egregious.widget.cpuwidget()
datewidget = egregious.widget.datewidget()
--musicwidget = egregious.widget.musicwidget()
--weatherwidget = egregious.widget.weatherwidget()
